spring:
  profiles:
    active: h2
  datasource:
    url: jdbc:mysql://localhost:3306/smartdogshop
    username: root
    password: 12345678
    driverClassName: com.mysql.jdbc.Driver

  mvc:
    view:
      prefix: /webPages/
      suffix: .jsp